theme:
  name: material
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/BodenmillerGroup/CISI_IMC
repo_name: BodenmillerGroup/CISI_IMC

use_directory_urls: false

plugins:
  - search

site_name: CISI IMC
nav:
    - Home: index.md
    - Tonsil th152 Preprocessing: results/reports/clean_inputs.html
    - Stability of Dictionary (Tonsil th152 Dataset): results/reports/analysis_U_stability_Tonsil_th152.html
    - Stability of Dictionary (Immmucan Lung Dataset): results/reports/analysis_U_stability_Immucan_lung.html
    - Immucan Lung Dataset: results/reports/analysis_lung.html
    - Tonsil th152 Dataset: results/reports/analysis_tonsil.html
    - Shared Markers in Immucan Lung and Tonsil Th152: results/reports/analysis_tonsil_vs_lung.html
    - Pilot Run for Immune Markers: results/reports/analysis_tonsil_pilot_immune_markers.html
    - Parameter Sweep (Proof-of-Concept): results/reports/parameter_sweep_evaluation_POC.html
    - Snakemake Report (Proof-of-Concept): results/reports/snakemake_report_POC.html
    - Parameter Sweep (Immune Markers): results/reports/parameter_sweep_evaluation_immune_channels.html
    - Snakemake Report (Immune Markers): results/reports/snakemake_report_immune_channels.html

markdown_extensions:
    - footnotes
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
