{
    "cisi_path": "/home/ubuntu/git/CISI_IMC/code",
    "sce_path": "/mnt/bb_dqbm_volume/data/Tonsil_th152/preprocessed_data/spe.h5ad",
    "masks_path": "/mnt/bb_dqbm_volume/data/Tonsil_th152/steinbock/masks_deepcell",
    "out_path": "/mnt/bb_dqbm_volume/analysis/Tonsil_th152/training/subset/proof_of_concept",
    "reports_path": "/home/ubuntu/git/CISI_IMC/results/reports",
    "proteins_of_interest": ["CD8a", "CD20", "CD4", "CD11c", "CD3", "Ki-67", "SMA", "panCK"],
    "parameter_sweep": {
        "k": [1, 2, 3, 4],
        "d": [5, 10, 20, 50, 80],
        "m": [4, 5, 6]
    },
    "default_params": {
        "split_by": "percentage",
        "k_cv": 4,
        "test_names": ["20220520_TsH_th152_cisi1_002"],
        "normalization": "none",
        "maxItr": 10,
        "maxcomposition": 2,
        "save": "no_noise",
        "analysis_normalization": False
    },
    "show_results": {
        "k": "",
        "d": "",
        "m": "4" 
    }
}
