on: 
  push: 
    branches: [html_hosting] 
  pull_request:
    branches: [html_hosting]

name: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      
      - name: copy files
        env:
          SRC_FOLDER_PATH: 'results/reports'
          TARGET_BRANCH: 'gh-pages'
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
      
      - name: mkdocs
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
